// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MLlikeGameplayTags
{	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ActionTaken_Shot);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_StatusEffect);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_StatusEffect_Curse);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_Shooting_MaxAmmo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_Shooting_MaxEnergy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_Shooting_FireDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_Shooting_FireDuration);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_Shooting_FirePeriod);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_MeleeCombo_FirstStepDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_MeleeCombo_SecondStepDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_MeleeCombo_ThirdStepDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_MeleeCombo_CurseTimer);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_MeleeCombo_CurseDamage);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Attribute_BaseHealth_MaxHealth);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Effects_AddMaxAmmo);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_EnergyAmountChanged_Message);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_MaxAmmoAmountChanged_Message);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MLlike_Ability_Shooting_OutOfAmmo);
};

