;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="AnimNotify.MeleeWindupSectionFinished",NewTagName="AnimNotify.MeleeWindupSectionEnded")
+GameplayTagRedirects=(OldTagName="GameplayEvents.Abilities.Melee.SignalAttack",NewTagName="GameplayEvent.Abilities.Melee.SignalAttack")
+GameplayTagRedirects=(OldTagName="GameplayCue.DamageNumber",NewTagName="GameplayCue.DamageType")
+GameplayTagRedirects=(OldTagName="GameplayCue.DamageNumber.Curse",NewTagName="GameplayCue.DamageType.Curse")
+GameplayTagRedirects=(OldTagName="GameplayCue.DamageNumber.Flat",NewTagName="GameplayCue.DamageType.Flat")
+GameplayTagRedirects=(OldTagName="GameplayCue.DamageNumber.Fire",NewTagName="GameplayCue.DamageType.Fire")
+GameplayTagList=(Tag="Abilities.Shoot.EnergyCost",DevComment="")
+GameplayTagList=(Tag="Abilities.Shoot.OutOfAmmo",DevComment="")
+GameplayTagList=(Tag="AnimNotify.MeleeComboEnded",DevComment="")
+GameplayTagList=(Tag="AnimNotify.MeleeWindupSectionEnded",DevComment="")
+GameplayTagList=(Tag="CharacterType.Enemy",DevComment="")
+GameplayTagList=(Tag="CharacterType.Player",DevComment="")
+GameplayTagList=(Tag="DamageType.Curse",DevComment="")
+GameplayTagList=(Tag="DamageType.Fire",DevComment="")
+GameplayTagList=(Tag="DamageType.Flat",DevComment="")
+GameplayTagList=(Tag="Effects.MeleeDamage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.CombatHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DamageType",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DamageType.Curse",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DamageType.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DamageType.Flat",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Abilities.Melee.SignalAttack",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Abilities.Shoot.SignalShooting",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.ComboWindowClosed",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.ComboWindowOpened",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.PlayerGotHit",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Punch",DevComment="")

